version: "3.8"

volumes:
  db:
    name: db

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_HOST: postgres
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres
    hostname: db
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
